language: generic
sudo: required

services:
  - docker

#before tests are run
#tag is used only inside travis so it could be shorter
before_install:
  #uses .env file so the test suite can be run, which is the whole purpose of Travis.
  #for a PROD build it'd be different (wouldn't be able to run the test suite in the same container).
  - docker build -t crkepler/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true crkepler/docker-react npm run test

#EBS will look at the docker-compose.yml file to make its own deployment, apart from Travis
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-520156139039"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"



