sudo: required
language: generic

services:
  - docker

#tag is used only inside travis so it could be shorter
before_install:
  - docker build -t crkepler/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true crkepler/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-520156139039"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"



