version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      #- "3000:3000"
      - "80:80"
    volumes:
      - /app/node_modules
      - .:/app
  #create a separate container just for test
  tests:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ['npm', 'run', 'test']